### ISSUE TITLE
Workspace-Support

### ISSUE THREAD

**Issue by markusmuellerw** [snowflakeOps/typo3-varnish#23]
Hi!
I think, there is a problem with cache-clearing (with enabled workspaces).
If there is a change on an dataset in draft-workspace, the TYPO3-DataHandler determines the cacheCmd "-1" (because this is the pid of datasets in workspaces != live), so EXT:varnish clears the whole cache, which is not the optimal workflow for performance issues.
Better it whould be, if EXT:varnish parses the cacheCmd for keywords like "all", "pages" for clearing the whole cache.

Greets,
Markus

**Comment by andristeiner** [comment]
Thanks for reporting. I'll take a look at it while releasing the next version. If your or anyone can provide any PRs in between, im happy to merge them.
