### ISSUE TITLE
Register snowflakeOps/typo3-varnish on packagist

### ISSUE THREAD

**Issue by kjeldschumacher** [snowflakeOps/typo3-varnish#36]
Hello,
I tried to require your extension via `composer require snowflakeops/varnish` but it appears that the vendor and extension ist not registered at packagist.org. I could use `typo3-ter/varnish`, but as I know this type of call is not recommended.

Could you please register your vendor and extension on packagist?

For more information please take a look at: http://elmars-typo3-knowledge-collection.readthedocs.io/en/latest/ContinuousIntegration/Composer-Github-Packagist.html
https://packagist.org/?q=snowflakeOps&p=0

Thanks in advance.

**Comment by andristeiner** [comment]
Hi Kjeld,

Thank you for pointing this out. Our vendor and the varnish packages is registred now:
https://packagist.org/packages/snowflakeops/varnish

As im not familiar with composer through packagist so far, please let me know if there are still any issues.

**Comment by kjeldschumacher** [comment]
Hi Andri, just to let you know. I tried `composer require snowflakeops/varnish` and it worked. 
Thank you for your fast feedback,
