### ISSUE TITLE
Varnish and pageNotFoundHandling

### ISSUE THREAD

**Issue by madaxel** [snowflakeOps/typo3-varnish#41]
Hi there,
I have a site where I configured TYPO3 to include another URL as 404 Page
`$GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFound_handling']  = URL to load`

The URL points to the same TYPO3 and loads correct.
Inspecting the directly loaded Headers I can see the TYPO3-Sitename and TYPO3-Pid Headers, but if the page is loaded via the pageNotFound Handler it will remove the header data.

Debugging into that I found the typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php Line 2048 (using TYPO3 8.7.6) where all headers except ContentType will be removed.
`                // Forward these response headers to the client
                $forwardHeaders = [
                    'Content-Type:'
                ];` ff.

The problem now is, that the not existing page is cached by varnish with content of the 404 Page and the clear varnish cache button in the backend will not delete this entry, because the TYPO3-Sitename is not correct.

I would expect, that every request through varnish will get tagged with TYPO3-Pid and TYPO3-Sitename. Maybe an additional pagenotFoundHandler implementation would solve this problem, which in my opinion would be a feature of this extension.

If you need more informations please let me know.

Thanks
Markus

**Comment by andristeiner** [comment]
Hi Markus,

Thanks for pointing this out. Personally, i'm missing a pageNotFound_handling configuration which renders a full site within the current request to get rid of the HTTP sub request which can led to many more other problems.

I'll try to reconstruct this problem and talk to some people more experienced with the TYPO3 core than me about the best way to move forward.

Cheers,
Andri

**Comment by andristeiner** [comment]
Hi Markus,

On my test installation, and also on some actual sites im running, 404 pages are not cached at all. I did not ran into this problem at all by now therefore. I think something must be missing on your end, please check:

* if a correct 404 header is issued by TYPO3 (maybe it gets overwritten, .e.g by [FE][pageNotFound_handling_statheader])
    * by answering with a 404 status, Varnish should not cache this particular answer at all
* if you're Varnish configuration includes [this part](https://github.com/snowflakeOps/typo3-varnish/blob/master/Resources/Private/Example/default-4.vcl#L133) out of the sample configuration
    * Varnish should cache answers only if there is a TYPO3-Pid header present. According to your description and also my tests, this header is missing on pageNotFound_handling answers, therefore it should not end up cached if this configuration is present

Please let me know your findings, so we can either close this issue or take further investigations.

**Comment by madaxel** [comment]
Hi Andri,
but why not cache the 404 pages. Just imagine a bot crawling invalid URLs. This would result in an significant increase of load on the server. That is why we try to cache the 404 pages.

I would like to leave this issue open, cause caching 404 seems to be very useful to me.

You are right, that the 404 Header overwrites the TYPO3-Pid and TYPO3-Sitename at the Code I pointed out earlier. So I think we should copy the code from the TypoScriptFrontendController.php to a new controller in your extension and let the User/Admin decide which way to go by defining the setting in the install tool.

ex. userfunc->Snowflake\Varnish\Varnish->pageNotFound

**Comment by andristeiner** [comment]
To keep things simple, we cache exactly those things as cached by TYPO3 internally. While this does not apply to a 404 answer of a certain URL, it is in place for the 404 url itself. If you're worried about 404 performance, you can make sure that the pageNotFound handling will fetch the 404 page through Varnish as well, so you don't have to render the whole page at least.

I try to keep everything in this extension as simple as possible, i don't really like to copy and modify core code therefore, and i don't think this case can justify the additional hassle of introducing, supporting and maintaining this additional feature.

**Comment by madaxel** [comment]
Hi Andri,
thanks for clarification. So if we do not cache 404 Status code pages that is ok, because in the background TYPO3 says "404" and the 404 Page fetched will be delivered from varnish as 200 with Pid and Sitename.

So load seems to be only TYPO3 checking if an url exists. Which should be fast using CoolUri or Real URL.

I adjusted the varnish setting at or place accordingly.
Thx
